import os
from pathlib import Path

android_dir = Path(os.environ["ANDROID_DIR"])
www = android_dir / "app/src/main/assets/www"
index = www / "index.html"
if not index.exists():
    raise SystemExit("ERRO: index.html nao encontrado")

css = r'''
:root{--pg-green:#17c873;--pg-dark:#0c131d;--pg-panel:#141f2c;--pg-text:#f6f8fa;--pg-muted:#aab5c2;--pg-gold:#f3c969}
.ms-profile-btn{position:fixed;left:14px;bottom:22px;z-index:99989;border:0;border-radius:999px;background:#1b2634;color:#fff;padding:12px 15px;font-weight:900;box-shadow:0 8px 28px #0008;border:1px solid #ffffff18}
.ms-prog{position:fixed;z-index:99994;inset:8px;background:var(--pg-dark);color:var(--pg-text);border:1px solid #ffffff18;border-radius:20px;box-shadow:0 20px 60px #000d;display:none;overflow:hidden;font-family:system-ui,sans-serif}.ms-prog.open{display:flex;flex-direction:column}
.ms-prog-head{display:flex;align-items:center;justify-content:space-between;padding:13px 15px;border-bottom:1px solid #ffffff12}.ms-prog-head h2{font-size:17px;margin:0}.ms-prog-close{background:transparent;border:0;color:#fff;font-size:25px}
.ms-prog-scroll{overflow:auto;padding:13px}.ms-hero-card{border-radius:18px;overflow:hidden;border:1px solid #ffffff18;background:#17212e}.ms-stadium{min-height:245px;position:relative;display:flex;align-items:flex-end;justify-content:center;padding:16px;background:linear-gradient(#253544,#14202b 58%,#31583b 59%,#183525)}
.ms-stadium:before{content:'';position:absolute;left:0;right:0;top:42%;height:42%;background:repeating-linear-gradient(90deg,#ffffff0c 0 3px,transparent 3px 34px);border-top:3px solid #ffffff1c}
.ms-stadium.campo_bairro{background:linear-gradient(#5f7890,#374b57 58%,#4d7545 59%,#325b36)}.ms-stadium.arquibancada_local{background:linear-gradient(#35495d,#1e2c39 56%,#326746 57%,#17432c)}.ms-stadium.estadio_municipal{background:radial-gradient(circle at 50% 18%,#ffffff55 0 3px,transparent 4px),linear-gradient(#233b53,#152331 55%,#2b7446 56%,#14512e)}.ms-stadium.arena_regional{background:radial-gradient(circle at 20% 13%,#fff8 0 2px,transparent 3px),radial-gradient(circle at 80% 13%,#fff8 0 2px,transparent 3px),linear-gradient(#1f3348,#121c27 54%,#237747 55%,#0f4b29)}.ms-stadium.arena_moderna{background:radial-gradient(ellipse at 50% 18%,#8fdcff55,transparent 52%),linear-gradient(#17283a,#0c1420 52%,#168149 53%,#0b4626)}.ms-stadium.estadio_internacional{background:radial-gradient(ellipse at 50% 15%,#d7e9ff66,transparent 55%),linear-gradient(#111e30,#080f19 50%,#188a4e 51%,#0a3f23)}.ms-stadium.arena_lendaria{background:radial-gradient(ellipse at 50% 10%,#ffd76b66,transparent 55%),linear-gradient(#1c1820,#090b10 49%,#148b4a 50%,#07371d)}.ms-stadium.arena_final_mundial{background:radial-gradient(ellipse at 50% 8%,#fff2a888,transparent 50%),linear-gradient(#241b13,#090909 48%,#159954 49%,#06351d)}.ms-stadium.estadio_chuva{background:linear-gradient(#29333f99,#0d1622),repeating-linear-gradient(110deg,#ffffff22 0 1px,transparent 1px 9px),linear-gradient(#223144,#0f1b28 55%,#1b6f43 56%,#0d4026)}.ms-stadium.estadio_neon{background:radial-gradient(circle at 15% 20%,#00e1ff88,transparent 18%),radial-gradient(circle at 85% 20%,#ff36d188,transparent 18%),linear-gradient(#10172b,#070a13 52%,#0b6b48 53%,#053523)}.ms-stadium.estadio_celestial{background:radial-gradient(ellipse at 50% 10%,#fff8c888,transparent 40%),linear-gradient(#27395e,#11192e 48%,#159954 49%,#06351d)}
.ms-avatar-wrap{position:relative;z-index:2;width:150px;text-align:center}.ms-avatar{width:142px;height:190px;filter:drop-shadow(0 8px 13px #0009)}.ms-stage-name{font-weight:1000;font-size:18px;margin-top:-5px;text-shadow:0 2px 4px #000}.ms-level-big{color:var(--pg-green);font-weight:1000;font-size:13px}.ms-hero-info{padding:12px 14px}.ms-wallet{display:flex;justify-content:space-between;gap:8px;font-size:12px;margin-bottom:8px}.ms-passbar{height:8px;border-radius:99px;background:#ffffff12;overflow:hidden}.ms-passfill{height:100%;background:linear-gradient(90deg,var(--pg-green),#65e5a4)}
.ms-section{margin-top:14px}.ms-section-title{font-weight:1000;font-size:14px;margin-bottom:9px}.ms-free-tag{font-size:9px;background:var(--pg-green);color:#07130c;border-radius:999px;padding:3px 7px;font-weight:1000;margin-left:6px}.ms-rewards{display:flex;gap:9px;overflow:auto;padding-bottom:6px}.ms-reward{min-width:122px;background:#ffffff08;border:1px solid #ffffff12;border-radius:14px;padding:10px}.ms-reward.locked{opacity:.42;filter:grayscale(.4)}.ms-reward-lvl{font-size:9px;color:var(--pg-muted);font-weight:900}.ms-reward-icon{font-size:28px;margin:7px 0}.ms-reward-name{font-size:11px;font-weight:900;min-height:30px}.ms-equip{margin-top:7px;width:100%;border:0;border-radius:9px;background:#ffffff12;color:#fff;padding:7px;font-size:10px;font-weight:900}.ms-equip.active{background:var(--pg-green);color:#07130c}
.ms-store-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.ms-store-item{background:#ffffff08;border:1px solid #ffffff12;border-radius:14px;padding:10px}.ms-store-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.ms-store-icon{font-size:30px}.ms-rarity{font-size:8px;padding:3px 6px;border-radius:999px;background:#ffffff12;color:#dce5ee;font-weight:900}.ms-store-price{color:var(--pg-gold);font-size:11px;font-weight:1000;margin-top:6px}.ms-buy{margin-top:8px;width:100%;border:0;border-radius:9px;background:var(--pg-gold);color:#1a1404;padding:8px;font-size:10px;font-weight:1000}.ms-buy.owned{background:#ffffff12;color:#fff}.ms-buy:disabled{opacity:.5}
.ms-predict-card{background:#ffffff08;border:1px solid #ffffff12;border-radius:15px;padding:12px}.ms-predict-row{display:grid;grid-template-columns:1fr 56px 18px 56px;align-items:center;gap:7px}.ms-score-input{width:100%;box-sizing:border-box;background:#ffffff0b;color:#fff;border:1px solid #ffffff18;border-radius:10px;padding:9px;text-align:center;font-weight:1000;font-size:17px}.ms-predict-save{margin-top:9px;width:100%;border:0;border-radius:11px;padding:10px;background:var(--pg-green);color:#07130c;font-weight:1000}.ms-predict-help{font-size:10px;color:var(--pg-muted);margin-top:7px;line-height:1.35}
@media(max-width:380px){.ms-store-grid{grid-template-columns:1fr}}
'''
(www / "beta-progression.css").write_text(css, encoding="utf-8")

js = r'''
(()=>{
 const BACKEND=localStorage.getItem('ms_beta_backend')||'https://matchscope-kjf9.onrender.com';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uid=()=>{let v=localStorage.getItem('ms_uid');if(!v){v='u_'+Date.now().toString(36)+Math.random().toString(36).slice(2,9);localStorage.setItem('ms_uid',v)}return v};
 let profile=null,battle=null,store=null,lastFixture='';
 const stageColor=t=>['#88929d','#8aa6b8','#49a56d','#2fbe72','#20ce78','#12d783','#d6a843','#efb843','#ffd867'][Math.max(0,Math.min(8,(t||1)-1))];
 function playerSvg(p){const tier=p?.stage?.tier||1,c=stageColor(tier),gold=tier>=7?'#f2c45f':'#e9eef3',star=tier>=5?'★':'',crown=tier>=9?'♛':'';return `<svg class="ms-avatar" viewBox="0 0 150 200" xmlns="http://www.w3.org/2000/svg"><ellipse cx="75" cy="190" rx="52" ry="8" fill="#0005"/><circle cx="75" cy="38" r="22" fill="#d2a47d"/><path d="M54 34q4-26 22-25q21 3 22 25q-11-9-22-7q-13-1-22 7" fill="#29231f"/><path d="M44 73q31-18 62 0l9 74H35z" fill="${c}" stroke="${gold}" stroke-width="3"/><path d="M45 77L22 130l17 8l24-48M105 77l23 53l-17 8l-24-48" fill="${c}" stroke="${gold}" stroke-width="3"/><path d="M53 144l-8 47h21l9-45M97 144l8 47H84l-9-45" fill="#171d26" stroke="${gold}" stroke-width="3"/><text x="75" y="116" fill="${gold}" text-anchor="middle" font-size="34" font-weight="900">${tier>=9?'10':tier}</text><text x="75" y="69" fill="#ffe072" text-anchor="middle" font-size="20">${star}</text><text x="75" y="24" fill="#ffe072" text-anchor="middle" font-size="25">${crown}</text></svg>`}
 function ensure(){if(document.getElementById('msProfileBtn'))return;document.body.insertAdjacentHTML('beforeend',`<button id="msProfileBtn" class="ms-profile-btn">⚽ Meu jogador</button><section id="msProg" class="ms-prog"><div class="ms-prog-head"><h2>Meu jogador</h2><button id="msProgClose" class="ms-prog-close">×</button></div><div id="msProgScroll" class="ms-prog-scroll"></div></section>`);document.getElementById('msProfileBtn').onclick=()=>{document.getElementById('msProg').classList.add('open');load()};document.getElementById('msProgClose').onclick=()=>document.getElementById('msProg').classList.remove('open')}
 function stadiumClass(){return profile?.equipped?.stadium||'campo_bairro'}
 function render(){if(!profile)return;const root=document.getElementById('msProgScroll');const rewards=battle?.rewards||profile.unlocked||[];const unlockedIds=new Set((profile.unlocked||[]).map(x=>x.id));const ownedIds=new Set((profile.owned||[]).map(x=>x.id));const left=profile.level>=200?'Nível máximo':`${Math.max(0,(profile.nextLevelXp||0)-(profile.currentLevelXp||0))} XP para o próximo nível`;root.innerHTML=`<div class="ms-hero-card"><div class="ms-stadium ${esc(stadiumClass())}"><div class="ms-avatar-wrap">${playerSvg(profile)}<div class="ms-stage-name">${esc(profile.stage?.name||'Iniciante')}</div><div class="ms-level-big">LVL ${profile.level} / 200</div></div></div><div class="ms-hero-info"><div class="ms-wallet"><span>🪙 ${Number(profile.coins||0)} MatchCoins</span><span>${esc(left)}</span></div><div class="ms-passbar"><div class="ms-passfill" style="width:${Math.round((profile.progress||0)*100)}%"></div></div></div></div><div class="ms-section"><div class="ms-section-title">Passe de evolução <span class="ms-free-tag">100% GRÁTIS</span></div><div class="ms-rewards">${rewards.map(r=>reward(r,unlockedIds.has(r.id))).join('')}</div></div><div class="ms-section"><div class="ms-section-title">Loja exclusiva 🪙</div><div class="ms-predict-help" style="margin-bottom:9px">Ganhe MatchCoins acertando palpites e subindo de nível. Use apenas dentro do MatchScope.</div><div class="ms-store-grid">${(store?.items||[]).map(i=>storeItem(i,ownedIds.has(i.id))).join('')}</div></div><div class="ms-section"><div class="ms-section-title">Palpite da partida</div>${predictionBox()}</div>`;root.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.type,b.dataset.id));root.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.id));const save=document.getElementById('msPredictSave');if(save)save.onclick=savePrediction}
 function reward(r,unlocked){const active=profile?.equipped?.[r.type]===r.id;return `<div class="ms-reward ${unlocked?'':'locked'}"><div class="ms-reward-lvl">LVL ${r.level}</div><div class="ms-reward-icon">${r.type==='stadium'?'🏟️':'👕'}</div><div class="ms-reward-name">${esc(r.name)}</div><button class="ms-equip ${active?'active':''}" ${unlocked?'':'disabled'} data-equip="1" data-type="${esc(r.type)}" data-id="${esc(r.id)}">${active?'Equipado':unlocked?'Equipar':'Bloqueado'}</button></div>`}
 function storeItem(i,owned){const active=profile?.equipped?.[i.type]===i.id;return `<div class="ms-store-item"><div class="ms-store-top"><span class="ms-store-icon">${esc(i.icon||'🎁')}</span><span class="ms-rarity">${esc(i.rarity||'Especial')}</span></div><div class="ms-reward-name">${esc(i.name)}</div><div class="ms-store-price">🪙 ${Number(i.price||0)}</div>${owned?`<button class="ms-equip ${active?'active':''}" data-equip="1" data-type="${esc(i.type)}" data-id="${esc(i.id)}">${active?'Equipado':'Equipar'}</button>`:`<button class="ms-buy" data-buy="1" data-id="${esc(i.id)}" ${(profile.coins||0)<(i.price||0)?'disabled':''}>${(profile.coins||0)>=(i.price||0)?'Comprar':'Faltam '+Math.max(0,(i.price||0)-(profile.coins||0))}</button>`}</div>`}
 function predictionBox(){const f=String(window.__msFixtureId||'').trim();if(!f)return `<div class="ms-predict-card"><div class="ms-predict-help">Abra uma partida para registrar um palpite.</div></div>`;return `<div class="ms-predict-card"><div class="ms-predict-row"><b>Placar</b><input id="msPh" class="ms-score-input" inputmode="numeric" min="0" max="20" type="number" value="0"><span>×</span><input id="msPa" class="ms-score-input" inputmode="numeric" min="0" max="20" type="number" value="0"></div><button id="msPredictSave" class="ms-predict-save">Salvar palpite</button><div class="ms-predict-help">Acertar vencedor/empate: +35 moedas. Placar exato: +80 moedas. Cada nível conquistado: +20 moedas.</div></div>`}
 async function load(){try{const r=await fetch(`${BACKEND}/chat/profile/${encodeURIComponent(uid())}`);if(r.ok){const j=await r.json();profile=j.profile;battle=j.battlePass;store=j.store;render()}}catch{}}
 async function equip(type,id){try{const r=await fetch(`${BACKEND}/chat/equip/${encodeURIComponent(uid())}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,id})});if(r.ok){const j=await r.json();profile=j.profile;render()}}catch{}}
 async function buy(id){try{const r=await fetch(`${BACKEND}/store/buy/${encodeURIComponent(uid())}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:id})});const j=await r.json();if(r.ok){profile=j.profile;render()}else if(j.profile){profile=j.profile;render()}}catch{}}
 async function savePrediction(){const f=String(window.__msFixtureId||'').trim(),h=Number(document.getElementById('msPh')?.value),a=Number(document.getElementById('msPa')?.value);if(!f||!Number.isInteger(h)||!Number.isInteger(a))return;const b=document.getElementById('msPredictSave');b.disabled=true;b.textContent='Salvando...';try{const r=await fetch(`${BACKEND}/predictions/${encodeURIComponent(f)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:uid(),home:h,away:a})});b.textContent=r.ok?'Palpite salvo ✓':'Não foi possível salvar'}catch{b.textContent='Sem conexão'}finally{setTimeout(()=>{b.disabled=false;if(b.textContent!=='Palpite salvo ✓')b.textContent='Salvar palpite'},1800)}}
 ensure();load();setInterval(()=>{const f=String(window.__msFixtureId||'').trim();if(f!==lastFixture){lastFixture=f;if(document.getElementById('msProg')?.classList.contains('open'))render()}},1000);
})();
'''
(www / "beta-progression.js").write_text(js, encoding="utf-8")

html=index.read_text(encoding="utf-8")
if 'beta-progression.css' not in html:
    html=html.replace('</head>','<link rel="stylesheet" href="beta-progression.css">\n</head>')
if 'beta-progression.js' not in html:
    html=html.replace('</body>','<script src="beta-progression.js"></script>\n</body>')
index.write_text(html,encoding="utf-8")
print("Progressao RPG, passe gratuito, loja MatchCoins, recompensas e palpites adicionados.")
