import os
from pathlib import Path

android_dir=Path(os.environ['ANDROID_DIR']); www=android_dir/'app/src/main/assets/www'; index=www/'index.html'
if not index.exists(): raise SystemExit('index.html nao encontrado')
css='''.ms-rpgx{margin-top:14px}.ms-rpgx-tabs{display:flex;gap:6px;overflow:auto;margin-bottom:9px}.ms-rpgx-tab{white-space:nowrap;border:0;border-radius:10px;padding:8px 10px;background:#ffffff10;color:#fff;font-weight:900;font-size:10px}.ms-rpgx-tab.on{background:#17c873;color:#07130c}.ms-rpgx-panel{display:none}.ms-rpgx-panel.on{display:block}.ms-rpgx-card{background:#ffffff08;border:1px solid #ffffff14;border-radius:14px;padding:10px;margin-bottom:8px}.ms-rpgx-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ms-rpgx-item{background:#ffffff08;border:1px solid #ffffff14;border-radius:13px;padding:9px}.ms-rpgx-icon{font-size:30px}.ms-rpgx-name{font-size:10px;font-weight:900}.ms-rpgx-meta{font-size:9px;color:#aab5c2}.ms-rpgx-btn{width:100%;margin-top:6px;border:0;border-radius:8px;padding:7px;background:#f3c969;color:#181203;font-size:9px;font-weight:1000}.ms-rpgx-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.ms-rpgx-stat{padding:9px;background:#ffffff08;border-radius:10px;font-size:10px}.ms-rpgx-stat b{display:block;font-size:17px;color:#f3c969}.ms-rank{display:grid;grid-template-columns:35px 1fr auto;gap:7px;padding:8px;border-bottom:1px solid #ffffff10;font-size:10px}.ms-rank b{color:#f3c969}.ms-quest{display:flex;justify-content:space-between;gap:8px;align-items:center}.ms-quest.done{opacity:.55}.ms-passmark{border-left:3px solid #f3c969}@media(max-width:360px){.ms-rpgx-grid{grid-template-columns:1fr}}'''
(www/'beta-rpg-daily.css').write_text(css,encoding='utf-8')
js=r'''(()=>{
const ITEMS=[['wizard_hat','🧙','Chapéu do Arquimago','Épico',0,0,0,5,10],['arcane_staff','🪄','Cajado Arcano','Lendário',0,0,0,10,20],['star_cloak','🧥','Manto das Estrelas','Épico',0,4,0,0,10],['floating_grimoire','📘','Grimório Flutuante','Raro',0,0,0,3,0],['celestial_crown','👑','Coroa Celestial','Lendário',6,6,6,6,20],['arcane_wings','🪽','Asas Arcanas','Épico',0,0,4,0,10],['champion_sword','⚔️','Espada do Campeão','Épico',8,0,0,0,10],['guardian_shield','🛡️','Escudo do Guardião','Raro',0,6,0,0,0],['titan_armor','🦾','Armadura do Titã','Lendário',0,10,0,0,20],['dragon_helm','🐉','Elmo do Dragão','Épico',0,5,0,0,10],['royal_cape','🧥','Capa Real','Raro',0,3,3,0,0],['knight_boots','🥾','Botas do Cavaleiro','Comum',0,0,2,0,0],['ninja_suit','🥷','Traje Ninja','Raro',0,0,4,0,0],['shadow_mask','🎭','Máscara das Sombras','Épico',0,0,5,0,10],['neon_katana','🗡️','Katana Neon','Lendário',8,0,0,0,20],['samurai_armor','🥋','Armadura Samurai','Épico',0,6,0,0,10],['ghost_aura','👻','Aura Fantasma','Raro',0,0,3,3,0],['arcane_eyes','👁️','Olhos Arcanos','Comum',0,0,0,2,0],['cosmic_helmet','🪐','Capacete Cósmico','Épico',0,5,0,0,10],['galactic_armor','🚀','Armadura Galáctica','Lendário',0,8,0,0,20],['jetpack','🎒','Mochila a Jato','Raro',0,0,5,0,0],['plasma_boots','🥾','Botas de Plasma','Épico',0,0,6,0,10],['lightning_aura','⚡','Aura de Raios','Lendário',5,5,5,5,20],['companion_drone','🤖','Drone Companheiro','Raro',0,0,3,3,0]];
const TOP=[['Trono Eterno','👑'],['Espada Lendária','⚔️'],['Armadura Divina','🦾'],['Asas da Vitória','🪽'],['Cetro Imperial','🪄'],['Capa do Campeão','🧥'],['Elmo Supremo','🐉'],['Aura Lendária','⚡'],['Manto Real','🧥'],['Emblema Épico','💠']];
const day=()=>new Date().toISOString().slice(0,10), month=()=>new Date().toISOString().slice(0,7);let st=JSON.parse(localStorage.getItem('ms_rpg_state')||'null')||{owned:['knight_boots'],eq:['knight_boots'],coins:0,season:0,day:'',quests:{}};if(st.day!==day()){st.day=day();st.quests={login:true,profile:false,stats:false,chat:false}};const save=()=>localStorage.setItem('ms_rpg_state',JSON.stringify(st));save();
function stats(){let a=[10,10,10,10],boost=0;ITEMS.filter(i=>st.eq.includes(i[0])).forEach(i=>{a[0]+=i[4];a[1]+=i[5];a[2]+=i[6];a[3]+=i[7];boost+=i[8]});return {a,boost:Math.min(25,boost),power:a.reduce((x,y)=>x+y,0)}}
function equip(id){if(!st.owned.includes(id))st.owned.push(id);st.eq=st.eq.includes(id)?st.eq.filter(x=>x!==id):[...st.eq,id].slice(-5);save();render()}
function root(){return document.getElementById('msProgScroll')}
function render(){let r=root();if(!r)return;let old=r.querySelector('.ms-rpgx');if(old)old.remove();let s=stats(),sec=document.createElement('div');sec.className='ms-section ms-rpgx';sec.innerHTML=`<div class="ms-section-title">⚔️ MatchScore RPG</div><div class="ms-rpgx-tabs"><button class="ms-rpgx-tab on" data-p="char">Personagem</button><button class="ms-rpgx-tab" data-p="quests">Desafios</button><button class="ms-rpgx-tab" data-p="pass">Passe</button><button class="ms-rpgx-tab" data-p="rank">Ranking</button></div><div class="ms-rpgx-panel on" data-v="char"><div class="ms-rpgx-card"><b>Poder Total: ${s.power}</b><div class="ms-rpgx-stats"><div class="ms-rpgx-stat">Força<b>${s.a[0]}</b></div><div class="ms-rpgx-stat">Defesa<b>${s.a[1]}</b></div><div class="ms-rpgx-stat">Velocidade<b>${s.a[2]}</b></div><div class="ms-rpgx-stat">Magia<b>${s.a[3]}</b></div></div><small>Boost ativo: +${s.boost}% XP (máx. 25%)</small></div><div class="ms-rpgx-grid">${ITEMS.map(i=>`<div class="ms-rpgx-item"><div class="ms-rpgx-icon">${i[1]}</div><div class="ms-rpgx-name">${i[2]}</div><div class="ms-rpgx-meta">${i[3]} · ${i[8]?`+${i[8]}% XP · `:''}FOR ${i[4]} DEF ${i[5]} VEL ${i[6]} MAG ${i[7]}</div><button class="ms-rpgx-btn" data-e="${i[0]}">${st.eq.includes(i[0])?'Remover':st.owned.includes(i[0])?'Equipar':'Testar/equipar'}</button></div>`).join('')}</div></div><div class="ms-rpgx-panel" data-v="quests">${quests()}</div><div class="ms-rpgx-panel" data-v="pass">${pass()}</div><div class="ms-rpgx-panel" data-v="rank">${rank()}</div>`;r.appendChild(sec);sec.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{sec.querySelectorAll('.ms-rpgx-tab,.ms-rpgx-panel').forEach(x=>x.classList.remove('on'));b.classList.add('on');sec.querySelector(`[data-v="${b.dataset.p}"]`).classList.add('on')});sec.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>equip(b.dataset.e));sec.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{st.quests[b.dataset.q]=true;st.coins+=25;st.season+=20;save();render()})}
function quests(){let q=[['profile','Personalizar o personagem',25],['stats','Consultar estatísticas no app',25],['chat','Participar da comunidade',25]];return `<div class="ms-rpgx-card"><b>Desafios diários</b><p class="ms-rpgx-meta">Renovam diariamente. Complete todos para o Baú Diário de 100 MatchCoins.</p></div>${q.map(x=>`<div class="ms-rpgx-card ms-quest ${st.quests[x[0]]?'done':''}"><span>${st.quests[x[0]]?'✅':'🎯'} ${x[1]}<br><small>+${x[2]} MatchCoins · +20 pontos sazonais</small></span><button class="ms-rpgx-btn" style="width:auto" data-q="${x[0]}" ${st.quests[x[0]]?'disabled':''}>${st.quests[x[0]]?'Feito':'Concluir'}</button></div>`).join('')}<div class="ms-rpgx-card">🪙 Carteira RPG de teste: <b>${st.coins}</b></div>`}
function pass(){let marks=[[25,'Baú 150 coins + item exclusivo'],[50,'Boost +5% XP + Baú 250'],[75,'Cosmético Épico exclusivo'],[100,'Equipamento Épico + Baú 400'],[125,'Boost +10% XP'],[150,'Equipamento Lendário + Baú 600'],[175,'Aura exclusiva do Passe'],[200,'Conjunto Lendário + Moldura Mestre + Baú 1000']];return `<div class="ms-rpgx-card"><b>Passe de Evolução · 100% gratuito</b><p class="ms-rpgx-meta">200 níveis. Missões diárias ajudam a avançar.</p></div>${marks.map(m=>`<div class="ms-rpgx-card ms-passmark"><b>LVL ${m[0]}</b><br><span class="ms-rpgx-meta">${m[1]}</span></div>`).join('')}`}
function rank(){return `<div class="ms-rpgx-card"><b>🏆 Temporada ${month()}</b><p class="ms-rpgx-meta">Termina no último dia do mês. Top 200 por Poder Total. Top 10 recebe itens exclusivos.</p></div>${TOP.map((x,i)=>`<div class="ms-rank"><b>#${i+1}</b><span>${x[1]} ${x[0]}</span><span>${i===0?'MELHOR ITEM':i<3?'LENDÁRIO':i<6?'ÉPICO':'RARO'}</span></div>`).join('')}<div class="ms-rpgx-card"><b>Ranking completo: Top 200</b><p class="ms-rpgx-meta">No beta local, posições reais serão preenchidas quando os perfis estiverem sincronizados com o servidor.</p></div>`}
let ob=new MutationObserver(()=>render());function start(){let r=root();if(r){ob.observe(r,{childList:true});render()}else setTimeout(start,400)}start();})();'''
(www/'beta-rpg-daily.js').write_text(js,encoding='utf-8')
html=index.read_text(encoding='utf-8')
if 'beta-rpg-daily.css' not in html: html=html.replace('</head>','<link rel="stylesheet" href="beta-rpg-daily.css?v=1"></head>')
if 'beta-rpg-daily.js' not in html: html=html.replace('</body>','<script src="beta-rpg-daily.js?v=1"></script></body>')
index.write_text(html,encoding='utf-8'); print('RPG, desafios, passe e ranking aplicados.')